### ISSUE TITLE
Update app-cutter after 2.0 release

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-app-cutter#15]
(Jason: @danielhollas I use this issue to track the things require to do to make this cutter more friendly and more fit with current infrastructures we have now, hope you don't mind). 

- [ ] ~~(TBD) using [`copier`](https://copier.readthedocs.io/en/stable/) which is using jinja like a template and [gets along well with `ruff` lint](https://github.com/astral-sh/ruff/issues/5824).~~
- [ ] Drop `setup.py` which not needed anymore with `aiidalab>=23.3.2`
- [ ] Use new notebook test framework used in AWB by installing app and loading notebook on the `full-stack` container.
- [x] Docs template using `mkdocs` as the backend.

**Comment by danielhollas** [comment]
This update should also include the GHA testing setup, according to what we currently have in AWB and QeApp (e.g. various helpful fixtures etc).

@unkcpz can you please add this issue to the Project? I am unable to edit this issue due to permissions.

**Comment by unkcpz** [comment]
Add the development team to the repo, you should have the permission now. Let me know if it is work.

**Comment by danielhollas** [comment]
As part of this, we can remove the `setup.py` file and add a minimal `pyproject.toml` instead.

```toml
[build-system]
# Version 62.6 is needed due to
# https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#opt-6
requires = [
    "setuptools>=64.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

As of pip 21.1 and setuptools>64.0.0, `setup.py` is not needed for editable installs anymore (in the new Docker stack we now have pip 22.0.4)
https://setuptools.pypa.io/en/latest/userguide/quickstart.html#development-mode
https://setuptools.pypa.io/en/latest/references/keywords.html
